---
title: "FoRTE"
---

On behalf of the Forest Threshold Resilience Experiment (FoRTE) team, we are writing to update you on project progress and plans, and to invite your partnership and collaboration. As a reminder, our project couples ecosystem modeling experiments with a large-scale disturbance manipulation at the University of Michigan Biological Station to evaluate the mechanisms underlying forest primary production resilience or decline across a gradient of disturbance severity. Our field manipulation will use girdling to target disturbance severity levels of 45, 65, and 85 % tree mortality. See: [NSF AWARD No. 1655095](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1655095&HistoricalAwards=false.)

 

Pre-treatment data collection in support of our four-year project begins this summer, with our girdling treatment scheduled for next Spring, 2019. This summer, our team will collect a variety of baseline data focused on characterizing pre-disturbance ecosystem structure and carbon cycling, including tree stem locations, leaf physiology and chemistry, above and belowground primary production, soil respiration, and lidar-derived canopy physical structure.

 

Our hope is that these data and the experimental manipulation to follow will serve as a platform for a variety of additional ecological and biogeochemical research. Also, in the interest of transparency and to facilitate data sharing, we are adopting an open field notebook approach, and will be posting methods, notes, code and data to our Github (https://github.com/FoRTExperiment) and/or Open Science Framework (https://osf.io/z8x73/) repositories. As we plan our 2018 field season, we are particularly interested in hearing from those of you with pre-treatment data requests, and we welcome your onsite data collection if your request is beyond the scope of our work.

